# Generated by Django 3.2.13 on 2022-05-04 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_review_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='taste',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
