# Generated by Django 3.2.13 on 2022-05-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fcstDate', models.TextField(blank=True, null=True)),
                ('fcstTime', models.TextField(blank=True, null=True)),
                ('temp', models.TextField(blank=True, null=True)),
                ('cloud', models.TextField(blank=True, null=True)),
                ('rain', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
