# Generated by Django 3.2.13 on 2022-05-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_rename_clean_review_cleaned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cleaned',
        ),
        migrations.RemoveField(
            model_name='review',
            name='price',
        ),
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
        migrations.RemoveField(
            model_name='review',
            name='taste',
        ),
    ]
