# Generated by Django 3.2.13 on 2022-05-05 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='review_id',
            field=models.ForeignKey(db_column='review_id_id', on_delete=django.db.models.deletion.CASCADE, to='review.review'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.ForeignKey(db_column='user_id_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_reviews',
            field=models.ManyToManyField(blank=True, related_name='like_users', through='member.Like', to='review.Review'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
