# Generated by Django 3.2.13 on 2022-05-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20220502_1356'),
        ('member', '0004_merge_0003_auto_20220502_1427_0003_auto_20220502_1431'),
        ('member', '0004_user_introduce'),
        ('member', '0007_alter_user_like_reviews'),
        ('member', '0007_remove_like_username'),
    ]

    operations = [
    ]
