# Generated by Django 3.2.13 on 2022-05-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20220504_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='clean',
            new_name='cleaned',
        ),
    ]
