# Generated by Django 3.2.13 on 2022-05-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_remove_like_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='username',
            field=models.ManyToManyField(related_name='_member_like_username_+', through='member.Like', to='member.Like'),
        ),
    ]
