# Generated by Django 3.2.13 on 2022-05-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20220504_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='clean',
        ),
        migrations.RemoveField(
            model_name='review',
            name='price',
        ),
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
        migrations.RemoveField(
            model_name='review',
            name='taste',
        ),
    ]
