# Generated by Django 3.2.13 on 2022-05-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20220502_1427'),
        ('member', '0003_auto_20220502_1431'),
    ]

    operations = [
    ]
