# Generated by Django 4.0.2 on 2022-04-28 20:22

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', member.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='like_reviews',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='review.Review'),
        ),
    ]
