# Generated by Django 3.2.13 on 2022-05-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', '남성'), ('f', '여성')], default='m', max_length=1),
        ),
    ]
