# Generated by Django 3.2.13 on 2022-05-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20220502_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='username',
        ),
    ]
