# Generated by Django 3.2.13 on 2022-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('member', '0006_like_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_reviews',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='review.Review'),
        ),
    ]
