# Generated by Django 3.2.13 on 2022-05-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_like_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='username',
        ),
    ]
