# Generated by Django 3.2.13 on 2022-05-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_name', models.TextField(blank=True, null=True)),
                ('s_tel', models.TextField(blank=True, null=True)),
                ('s_photo', models.TextField(blank=True, null=True)),
                ('s_hour', models.TextField(blank=True, null=True)),
                ('s_etc', models.TextField(blank=True, null=True)),
                ('s_menu', models.TextField(blank=True, null=True)),
                ('s_price', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('s_name', models.TextField()),
                ('s_add', models.TextField(null=True)),
                ('s_road', models.TextField()),
                ('s_kind', models.TextField()),
                ('lat', models.FloatField()),
                ('lot', models.FloatField()),
                ('s_status', models.TextField()),
                ('modification_time', models.DateTimeField()),
            ],
        ),
    ]
